### ISSUE TITLE
Block names will be removed when using multiple blockpacks

### ISSUE THREAD

**Issue by 3prm3** [KnowYourKnot/Blockpacks#6]
The names will instead show up as subnames.

**Comment by KnowYourKnot** [comment]
This is intended - totally forgot about it when mentioning localisation. This is what the en_us.json file *should* look like:
```
{
    "block.chiseldecor.test.cool_blocks": "Cool Block",
    "block.chiseldecor.test.cool_blocks.red_cool_block": "Red",
    "block.chiseldecor.test.cool_blocks.yellow_cool_block": "Yellow",
    "block.chiseldecor.test.cool_blocks.green_cool_block": "Green",
```

**Comment by 3prm3** [comment]
> This is intended - totally forgot about it when mentioning localisation. This is what the en_us.json file _should_ look like:
> 
> ```
> {
>     "block.chiseldecor.test.cool_blocks": "Cool Block",
>     "block.chiseldecor.test.cool_blocks.red_cool_block": "Red",
>     "block.chiseldecor.test.cool_blocks.yellow_cool_block": "Yellow",
>     "block.chiseldecor.test.cool_blocks.green_cool_block": "Green",
> }
> ```

K
